# Continuous delivery
name: Java CD

on:
  push:
    branches:
      - 'release/**'        # Release branches
      - workflow            # Workflow branch
      - master              # Main project branch
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    env:
      OS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Assemble classes
        run: ./gradlew classes --stacktrace
      - name: Run Unit Tests
        run: ./gradlew test --stacktrace
      - name: Generate changelog
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew generateChangelog --stacktrace
      - name: Assemble distribution
        run: ./gradlew assembleDist -x generateChangelog --stacktrace
      - name: Run FOSSA scan
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-umbrella
          directory: ./coverage/reports/
          files: ./coverage1.xml,./coverage2.xml
          path_to_write_report: ./coverage/codecov_report.txt
          flags: unittests
          env_vars: OS
          verbose: true
