name: Java CI

on:
  push:
    branches:
      - 'hotfix/**'         # Hotfix branches
      - 'work/**'           # Workflow branches
      - master              # Main project branch
      - dev                 # Development branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: 3.0
            bundler-cache: true
      - run: bundle exec rake
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
