on:
  workflow_dispatch:
  push:
    tags:
      # Versioned release tags
      - 'v*'

# Continuous delivery
name: Java CD

jobs:
  test:
    name: Unit test on platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      # Checkout repository
      - uses: actions/checkout@v2
      # Setup Java environment
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Assemble main classes with gradle
      - name: Assemble classes
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: classes --stacktrace
      # Cache gradle temporary files
      - name: Cache gradle files
        uses: actions/cache@v2
        with:
          path: |
            ./.gradle
            ./buildSrc/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Cache java compile output
      - name: Cache build files
        uses: actions/cache@v2
        with:
          path: |
            ./build/classes
            ./build/resources
            ./buildSrc/build
          key: ${{ runner.os }}-${{ github.sha }}
      # Run unit tests with gradle
      - name: Run Unit Tests
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: test --stacktrace
      # Upload test reports as run artifact
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report-${{ runner.os }}
          path: ./build/reports/tests/

  generate:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v2
      # Ruby is needed to generate changelog
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      # Generate project changelog with gradle
      - name: Generate changelog
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: generateChangelog --stacktrace

  build:
    name: Build and release on Linux
    runs-on: ubuntu-latest
    needs: [ test, generate ]
    steps:
      # Checkout repository
      - uses: actions/checkout@v2
        with:
          ref: master
      # Setup Java environment
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Ruby is needed to generate changelog
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      # Cache gradle temporary files
      - name: Cache gradle files
        uses: actions/cache@v2
        with:
          path: |
            ./.gradle
            ./buildSrc/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Cache java compile output
      - name: Cache build files
        uses: actions/cache@v2
        with:
          path: |
            ./build/classes
            ./build/resources
            ./buildSrc/build
          key: ${{ runner.os }}-${{ github.sha }}
      # Assemble the output of this project with gradle
      - name: Assemble distribution
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: assembleDist -x generateChangelog --stacktrace
      # Sync local and remote repository
      - name: Fetch and pull
        id: resolve-prev-tag
        run: git fetch && git pull origin
      # Read previous tag created in repository
      # Parse and see if it's a pre-release
      - name: Read last tag
        id: read-tag
        run: |
          echo ::set-output name=tag::$(git describe --abbrev=0 ${{ github.ref }}^)
          echo ::set-output name=ref::$(echo ${{ github.ref }} | cut -c 11-)
          echo ::set-output name=name::$(echo ${{ github.ref }} | cut -c 12-)
          if [[ ${{ github.ref }} =~ ^.*\-(alpha|beta|rc).*$ ]]; then
              echo ::set-output name=isPreRelease::true
          fi
      # Generate changelog including only latest tag
      - name: Generate release text
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundler exec github_changelog_generator -u yooksi -p pz-zdoc --since-tag=${{ steps.read-tag.outputs.tag }} --output ./release_text.md --no-unreleased --header-label ''
      # Remove notice from generated changelog
      - name: Trim release text
        run: |
          head -n -3 release_text.md > tmp.txt
          tail -n +4 tmp.txt > release_text.md
          less release_text.md
      # Create a release in Github repository
      - name: Create Github release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.read-tag.outputs.ref }}
          release_name: ${{ steps.read-tag.outputs.name }}
          prerelease: ${{ steps.read-tag.outputs.isPreRelease }}
          body_path: ./release_text.md
          draft: false
      # Upload distribution artifact to release
      - name: Upload distribution zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./build/distributions/pz-zdoc-${{ steps.read-tag.outputs.name }}.zip
          asset_name: pz-zdoc-${{ steps.read-tag.outputs.name }}.zip
          asset_content_type: application/zip
      # Upload distribution artifact to release
      - name: Upload distribution tar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./build/distributions/pz-zdoc-${{ steps.read-tag.outputs.name }}.tar
          asset_name: pz-zdoc-${{ steps.read-tag.outputs.name }}.tar
          asset_content_type: application/tar
