on:
  push:
    branches:
      # Development branch
      - dev

# Continuous integration
name: Java CI

jobs:
  build:
    name: Unit test on platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      # Checkout repository
      - uses: actions/checkout@v2
      # Setup Java environment
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Assemble main classes with gradle
      - name: Assemble classes
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: classes --stacktrace
      # Run unit tests with gradle
      - name: Run Unit Tests
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: test --stacktrace
      # Upload test reports as run artifact
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report-${{ runner.os }}
          path: ./build/reports/tests/
      # Generate code coverage report with gradle (Jacoco)
      - name: Generate coverage report
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: jacocoTestReport -x test --stacktrace
      # Upload generated coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-foss
          files: ./build/coverage.xml
          flags: unittests
          verbose: true
