on:
  push:
    branches:
      - 'release/**'        # Release branches
      - 'hotfix/**'         # Hotfix branches
      - master              # Main project branch

# Product inspection
name: Java PI

jobs:
  check:
    name: Check compliance
    runs-on: ubuntu-latest
    steps:
      # Run FOSSA scan and upload build data
      - name: Check license compliance
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
      # Check if code is spotless
      - name: Check code format compliance
        run: ./gradlew spotlessJavaCheck -PmakeSpotless=true
  test:
    name: Unit test on platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      # Checkout repository
      - uses: actions/checkout@v2
      # Setup Java environment
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Assemble main classes with gradle
      - name: Assemble classes
        run: ./gradlew classes --stacktrace
      # Run unit tests with gradle
      - name: Run Unit Tests
        run: ./gradlew test --stacktrace
      # Upload test reports as run artifact
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report-${{ runner.os }}
          path: ./build/reports/tests/
